### ISSUE TITLE
异常报错（

### ISSUE THREAD

**Issue by greenhandzdl** [whiterasbk/wolframalpha4mirai#1]
![IMG_20220125_230856](https://user-images.githubusercontent.com/61241103/151003804-29cbb571-05a6-45ac-b25d-fe534cb5e1f6.jpg)
我用的wolframalpha4mirai-with-org.json.jar，主程序MA，但仍然会报错。
希望能解决一下。

**Comment by whiterasbk** [comment]
@greenhandzdl 
已经解决并在 `MiraiAndroid` 上测试通过
使用 [这个发布版本](https://github.com/whiterasbk/wolframalpha4mirai/releases/download/1.2/wolframalpha.jar) 即可解决问题
另外由于 `Android` 平台上本身就带有 `org.json` 库, 理论上无需使用  `wolframalpha4mirai-with-org.json.jar` 这个版本

**Comment by greenhandzdl** [comment]
![75be0ae6112857b4.png](https://user-images.githubusercontent.com/61241103/151090951-8b4146e5-e00b-4470-ac9c-606b0297ac7c.png)
这个算不算异常¿

**Comment by whiterasbk** [comment]
@greenhandzdl 
这个不算做异常，出现的原因是wolframalpha官方对非英文查询支持得不太好，基本上不支持中文查询，建议使用全英文进行查询。当然后续版本有考虑添加先将输入文本进行翻译再发送到wolframalpha的选项

**Comment by 502milk** [comment]
![QQ截图20220130183451](https://user-images.githubusercontent.com/49502047/151696141-c1464355-a2ff-4974-a328-376eb7fdf75a.jpg)
![QQ截图20220130183524](https://user-images.githubusercontent.com/49502047/151696160-d887935c-0d1b-469a-a351-607e9aba0793.jpg)
不是很懂wolframalpha
