### ISSUE TITLE
本应搜到的内容却没有返回

### ISSUE THREAD

**Issue by 502milk** [whiterasbk/wolframalpha4mirai#2]
![QQ截图20220130183451](https://user-images.githubusercontent.com/49502047/151696199-84ae3206-e8ba-430c-a388-09355fd2da68.jpg)
![QQ截图20220130183524](https://user-images.githubusercontent.com/49502047/151696200-80617511-cd66-4a36-b837-bd36130f6189.jpg)
不是很懂wolframalph

**Comment by whiterasbk** [comment]
@502milk 
你好, 新年快乐~
经过本地测试，搜索`polybenzimidazole`的情况确实如图所描述的情况, `http://api.wolframalpha.com`和`http://api.wolframalpha.com`的结果不一样, 前者无法通过字符串检索出结果, 具体响应的数据为
```json
{
	"queryresult":{
		"success":false,
		"error":false,
		"numpods":0,
		"datatypes":"",
		"timedout":"",
		"timedoutpods":"",
		"timing":0.17400000000000002,
		"parsetiming":8.4e-2,
		"parsetimedout":false,
		"recalculate":"",
		"id":"MSP67881c41iaca7efi169e00004eg6cge4c9h0hgf5",
		"host":"https:\/\/www6b3.wolframalpha.com",
		"server":"7",
		"related":"",
		"version":"2.6",
		"inputstring":"polybenzimidazole",
		"didyoumeans":{
			"score":"0.",
			"level":"low",
			"val":"benzimidazole"
		}
	}
}
```
而后者使用的内部查询接口为`wss://www.wolframalpha.com/n/v1/api/fetcher/results`, 结果显示正常
![2IZ0%GRMKP3Z}@6R~LH557D](https://user-images.githubusercontent.com/31107204/152132965-e83170ff-4119-4cd6-988c-153b75d7549e.png)
原因有可能是因为wolframalpha内部对接口的实现不统一导致的bug.
无论如何, 此问题的需要依靠wolfram官方自行解决, 此插件仅仅是做了将关键词对接到`http://api.wolframalpha.com`并且返回其响应的结果的工作而已.
咱这里能改进的就是在api接口返回的`error`为`false`的情况下将上述响应的json的中的`didyoumeans`展示出来

**Comment by 502milk** [comment]
@whiterasbk 
新年好~
如果是这样的话也就只能等待官方去修复了
~~这刷锅标签笑死我了~~
